export const SET_FETCH_SUPPORT_ITEMS = 'SET_FETCH_SUPPORT_ITEMS';
export const SET_FETCH_SUPPORT_ITEMS_ERROR = 'SET_FETCH_SUPPORT_ITEMS_ERROR';
export const SET_SUPPORT_ITEMS_STATUS = 'SET_SUPPORT_ITEMS_STATUS';
