export const FETCH_SUPPORT_ITEMS = "FETCH_SUPPORT_ITEMS";
export const SET_FETCH_SUPPORT_ITEMS = "SET_FETCH_SUPPORT_ITEMS";
export const SET_FETCH_SUPPORT_ITEMS_ERROR = "SET_FETCH_SUPPORT_ITEMS_ERROR";
