export const POPULATE_PROSPECT_NOTES = 'POPULATE_PROSPECT_NOTES';
export const SET_PROSPECT_NOTE_ERROR = 'SET_PROSPECT_NOTE_ERROR';
export const SET_PROSPECT_NOTES_STATUS = 'SET_PROSPECT_NOTES_STATUS';
