export const SET_PROSPECT_DATA = 'SET_PROSPECT_DATA';
export const SET_PROSPECT_CAMPAIGNS = 'SET_PROSPECT_CAMPAIGNS';
export const SET_PROSPECT_DETAILS_TAB_AGENTS = 'SET_PROSPECT_DETAILS_TAB_AGENTS';
export const SET_PROSPECT_DETAILS_TAB_LEADSTAGES = 'SET_PROSPECT_DETAILS_TAB_LEADSTAGES';
export const SET_PROSPECT_FETCH_STATUS = 'SET_PROSPECT_FETCH_STATUS';
