export const FETCH_CAMPAIGN_FOLDERS = 'FETCH_CAMPAIGNS_FOLDER';
export const SET_FETCH_CAMPAIGN_FOLDERS = 'SET_FETCH_CAMPAIGN_FOLDER';
export const SET_FETCH_CAMPAIGN_FOLDERS_ERROR = 'SET_FETCH_CAMPAIGN_FOLDERS_ERROR';

export const DECREMENT_MARKET_CAMPAIGN_COUNT = 'DECREMENT_MARKET_CAMPAIGN_COUNT';
