import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import {
  faBullhorn,
  faSearch,
  faChevronUp,
  faPaperPlane,
  faQuestionCircle,
  faCheck,
  faCheckCircle,
  faUser,
  faBolt,
  faCommentDots,
  faStickyNote,
  faPhoneSlash,
  faStar,
  faTimesCircle,
  faTimes,
  faTags,
  faHeadset,
  faMobileAlt,
  faShare,
  faBell,
  faLayerGroup,
  faFilter,
  faEnvelope,
  faCreditCard,
  faExclamationTriangle,
  faBook,
  faTrash,
  faPencilAlt,
  faListUl,
  faEllipsisV,
  faChartBar,
  faPlusCircle,
  faUserCog

} from "@fortawesome/free-solid-svg-icons";

library.add(
  fab,
  faBullhorn,
  faSearch,
  faChevronUp,
  faPaperPlane,
  faQuestionCircle,
  faCheck,
  faCheckCircle,
  faUser,
  faBolt,
  faCommentDots,
  faStickyNote,
  faPhoneSlash,
  faStar,
  faTimesCircle,
  faTimes,
  faTags,
  faHeadset,
  faMobileAlt,
  faShare,
  faBell,
  faLayerGroup,
  faFilter,
  faEnvelope,
  faCreditCard,
  faExclamationTriangle,
  faBook,
  faTrash,
  faPencilAlt,
  faListUl,
  faEllipsisV,
  faChartBar,
  faPlusCircle,
  faUserCog

);
