export const SET_ACTIVE_CAMPAIGN = 'SET_ACTIVE_CAMPAIGN';
export const SET_ACTION_BTN_STATUS = 'SET_ACTION_BTN_STATUS';
export const SET_ACTIVE_PROSPECT = 'SET_ACTIVE_PROSPECT';
export const CLEAR_ACTIVE_CAMPAIGN = 'CLEAR_ACTIVE_CAMPAIGN';
