export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const SET_FETCH_CAMPAIGNS = 'SET_FETCH_CAMPAIGNS';
export const SET_FETCH_CAMPAIGNS_ERROR = 'SET_FETCH_CAMPAIGNS_ERROR';
export const RESET_CAMPAIGNS_DATA = 'RESET_CAMPAIGNS_DATA';
export const ARCHIVE_CAMPAIGN = 'ARCHIVE_CAMPAIGN';
export const UPDATE_SMS_TEMPLATE = 'UPDATE_SMS_TEMPLATE';

// lazy loading more
export const SET_FETCH_CAMPAIGNS_NEXT_PAGE = 'SET_FETCH_CAMPAIGNS_NEXT_PAGE';
export const SET_FETCH_CAMPAIGNS_NEXT_PAGE_ERROR = 'SET_FETCH_CAMPAIGNS_NEXT_PAGE_ERROR';
export const SET_FETCH_CAMPAIGNS_NEXT_PAGE_SUCCESS = 'SET_FETCH_CAMPAIGNS_NEXT_SUCCESS';
