export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const SET_FETCH_CAMPAIGNS = 'SET_FETCH_CAMPAIGNS';
export const SET_FETCH_CAMPAIGNS_ERROR = 'SET_FETCH_CAMPAIGNS_ERROR';
export const RESET_CAMPAIGNS_DATA = 'RESET_CAMPAIGNS_DATA';
