export const POPULATE_CAMPAIGN_NOTES = 'POPULATE_CAMPAIGN_NOTES';
export const SET_CAMPAIGN_NOTE_ERROR = 'SET_CAMPAIGN_NOTE_ERROR';
export const SET_CAMPAIGN_NOTES_STATUS = 'SET_CAMPAIGN_NOTES_STATUS';
